server:
  port: 8080
spring:
  main:
    banner-mode: off
  config:
    activate:
      on-profile: 'test'
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/wallet-timeline'
      auto-index-creation: true
      database: wallet-timeline
  rabbitmq:
    host: rabbitmq-wallet
    port: 5672
  redis:
    host: redis-wallet
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 120000
amqp:
  financialMovement:
    exchange:
      name: ex.financialMovement
    queues:
      wallet-timeline:
        name: rk.wallettimeline
        deadLetter: dlq.wallettimeline