server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
      name: wallet-timeline
  config:
    activate:
      on-profile: 'prod'
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://wallet-db:27017/wallet-timeline?authSource=admin
      authentication-database: admin
      database: wallet-timeline
  rabbitmq:
    username: rabbitmq
    password: admin@rabbitmq
    host: localhost
    port: 5672
  redis:
    host: redis-wallet
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 120000
amqp:
  financialMovement:
    exchange:
      name: ex.financialMovement
    queues:
      wallet-timeline:
        name: rk.wallettimeline
        deadLetter: dlq.wallettimeline

