version: '3.3'

networks:
  localhost-network:
  wallet:
    driver: bridge
  wallet-user:
    driver: bridge

volumes:
  database:

services:
  wallet-db:
    image: mongo:bionic
    container_name: wallet-db
    hostname: wallet-db
    ports:
      - "27017:27017"
    volumes:
      - database:/data/wallet-db
    networks:
      - localhost-network
      - wallet-user

  rabbitmq-wallet:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-wallet
    hostname: rabbitmq-wallet
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=admin@rabbitmq
    networks:
      - localhost-network
      - wallet-user
  
  wallet-user-app:
    image: openjdk:11-jre
    container_name: wallet-user-app
    hostname: wallet-user-app
    volumes: 
      - ./wallet-user/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 15 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-user.jar"
    ports:
      - "8056:8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
    networks:
      - localhost-network
      - wallet-user
