version: '3'

networks:
  localhost-network:
    driver: bridge
  wallet:
    driver: bridge
  wallet-user:
    driver: bridge
  default:
    external: true

volumes:
  database:

services:
  mongo-db-wallet-user:
    image: mongo:5.0.3
    container_name: mongo-db-wallet-user
    ports:
      - "27017:27017"
    volumes:
      - database:/data/mongo-db-wallet-user
    environment:
      - MONGO_INITDB_DATABASE=wallet-user
      - MONGO_INITDB_USER=wallet-user
      - MONGO_INITDB_PASSWORD=wallet-user
    networks:
      - localhost-network
      - wallet-user

  rabbitmq-wallet:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-wallet
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=admin@rabbitmq
    networks:
      - localhost-network
      - wallet-user
  
  wallet-user-app:
    image: openjdk:17-alpine3.14
    container_name: wallet-user-app
    volumes: 
      - ./wallet-user/target:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - MONGODB_URI=mongodb://wallet-user:wallet-user@wallet-user-db/wallet-user?authSource=admin
      - RABBITMQ_HOST=rabbitmq-wallet
    command:
      - "java"
      - "-jar"
      - "/usr/src/app/wallet-user.jar"
    ports:
      - "8056:8080"
    depends_on:
      - rabbitmq-wallet
      - mongo-db-wallet-user
    networks:
      - localhost-network
      - wallet-user
