version: "3"

networks:
  localhost-network:
    driver: bridge
  wallet:
    driver: bridge
  wallet-db:
    driver: bridge
  wallet-rabbit:
    driver: bridge
  redis-wallet:
    driver: bridge

volumes:
  database:

services:
  wallet-db:
    image: mongo:bionic
    container_name: wallet-db
    hostname: wallet-db
    ports:
      - "27017:27017"
    volumes:
      - database:/data/wallet-db
    networks:
      - wallet-db

  rabbitmq-wallet:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-wallet
    hostname: rabbitmq-wallet
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=admin@rabbitmq
    networks:
      - localhost-network
      - wallet-rabbit
  
  redis-wallet:
    image: redis:alpine
    container_name: redis-wallet
    hostname: redis-wallet
    command: redis-server
    ports:
      - "6379:6379"
    networks:
    - redis-wallet

  wallet-user-app-1:
    image: openjdk:11-jre
    container_name: wallet-user-app-1
    hostname: wallet-user-app-1
    restart: always
    volumes:
      - ./wallet-user/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-user.jar"
    ports:
      - "8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  wallet-user-app-2:
    image: openjdk:11-jre
    container_name: wallet-user-app-2
    hostname: wallet-user-app-2
    restart: always
    volumes:
      - ./wallet-user/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-user.jar"
    ports:
      - "8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  wallet-timeline-1:
    image: openjdk:11-jre
    container_name: wallet-timeline-1
    hostname: wallet-timeline-1
    restart: always
    volumes:
      - ./wallet-timeline/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 7 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-timeline.jar"
    ports:
      - "8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
      - redis-wallet
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet
      - redis-wallet
  
  bill-payment-1:
    image: openjdk:11-jre
    container_name: bill-payment-1
    hostname: bill-payment-1
    restart: always
    volumes:
      - ./bill-payment/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/bill-payment.jar"
    ports:
      - "8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  bill-payment-2:
    image: openjdk:11-jre
    container_name: bill-payment-2
    hostname: bill-payment-2
    restart: always
    volumes:
      - ./bill-payment/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/bill-payment.jar"
    ports:
      - "8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  wallet-timeline-2:
    image: openjdk:11-jre
    container_name: wallet-timeline-2
    hostname: wallet-timeline-2
    restart: always
    volumes:
      - ./wallet-timeline/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 7 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-timeline.jar"
    ports:
      - "8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
      - redis-wallet
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet
      - redis-wallet

  wallet-gateway:
    image: nginx
    container_name: wallet-gateway
    hostname: wallet-gateway
    volumes:
      - ./wallet-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - localhost-network
      - wallet
    depends_on:
      - wallet-user-app-1
      - wallet-user-app-2
      - wallet-timeline-1
      - wallet-timeline-2
