server:
  port: 8080
spring:
  main:
    banner-mode: off
  config:
    activate:
      on-profile: 'test'
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/wallet-user'
      auto-index-creation: true
