server:
  port: 8080
  netty:
    connection-timeout: 2m
spring:
  config:
    activate:
      on-profile: 'prod'
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb://wallet-user:wallet-user@123@127.0.0.1/wallet-user?authSource=admin}