server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
      name: waller-user
  config:
    activate:
      on-profile: 'local'
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27017/wallet-user?authSource=admin
      authentication-database: admin
  rabbitmq:
    username: rabbitmq
    password: admin@rabbitmq
    host: localhost
    port: 5672

amqp:
  financialMovement:
    exchange:
      name: ex.financialMovement
    queues:
      wallet-timeline:
        name: rk.wallettimeline
        deadLetter: dlq.wallettimeline

