server:
  port: ${WalletUserApplication:8080}
  netty:
    connection-timeout: 2m
spring:
  main:
    banner-mode: off
  application:
      name: waller-user
  config:
    activate:
      on-profile: 'prod'
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      uri: ${MONGODB_URI:mongodb://wallet-user:wallet-user@127.0.0.1/wallet-user?authSource=admin}