server:
  port: ${WalletUserApplication:8080}
  netty:
    connection-timeout: 2m
spring:
  config:
    activate:
      on-profile: 'test'
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/wallet-user'
      auto-index-creation: true
