server:
  port: 8080
spring:
  application:
      name: waller-user
  config:
    activate:
      on-profile: 'prod'
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://wallet-db:27017/wallet-user?authSource=admin
      authentication-database: admin
  rabbitmq:
    username: rabbitmq
    password: admin@rabbitmq
    host: rabbitmq-wallet
    port: 5672

amqp:
  financialMovement:
    exchange:
      name: ex.financialMovement
    queues:
      wallet-timeline:
        name: rk.wallettimeline
        deadLetter: dlq.wallettimeline
