server:
  port: ${WalletUserApplication:8080}
  netty:
    connection-timeout: 2m
spring:
  config:
    activate:
      on-profile: 'prod'
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      database: wallet-user
      username: wallet-user
      password: wallet-user