server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
      name: waller-user
  config:
    activate:
      on-profile: 'prod'
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://wallet-db:27017/wallet-user?authSource=admin
      authentication-database: admin