version: "3"

networks:
  localhost-network:
    driver: bridge
  wallet:
    driver: bridge
  wallet-db:
    driver: bridge
  wallet-rabbit:
    driver: bridge
  redis-wallet:
    driver: bridge

volumes:
  database:

services:
  wallet-user-app-1:
    image: wallet-user:1.0.0
    container_name: wallet-user-app-1
    hostname: wallet-user-app-1
    restart: always
    volumes:
      - ./wallet-user/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-user.jar"
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq-wallet
      - wallet-db
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  wallet-user-app-2:
    image: wallet-user:1.0.0
    container_name: wallet-user-app-2
    hostname: wallet-user-app-2
    restart: always
    volumes:
      - ./wallet-user/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-user.jar"
    ports:
      - "8080"
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  wallet-timeline-1:
    image: wallet-timeline:1.0.0
    container_name: wallet-timeline-1
    hostname: wallet-timeline-1
    restart: always
    volumes:
      - ./wallet-timeline/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 7 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-timeline.jar"
    ports:
      - "8082:8080"
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet
      - redis-wallet

  wallet-timeline-2:
    image: wallet-timeline:1.0.0
    container_name: wallet-timeline-2
    hostname: wallet-timeline-2
    restart: always
    volumes:
      - ./wallet-timeline/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 7 && java -jar -Dspring.profiles.active=prod /opt/app/wallet-timeline.jar"
    ports:
      - "8080"
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet
      - redis-wallet

  bill-payment-1:
    image: bill-payment:1.0.0
    container_name: bill-payment-1
    hostname: bill-payment-1
    restart: always
    volumes:
      - ./bill-payment/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/bill-payment.jar"
    ports:
      - "8083:8080"
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet

  bill-payment-2:
    image: bill-payment:1.0.0
    container_name: bill-payment-2
    hostname: bill-payment-2
    restart: always
    volumes:
      - ./bill-payment/target:/opt/app
    working_dir: /opt
    environment:
      - RABBITMQ_HOST=rabbitmq-wallet
    command: bash -c "sleep 5 && java -jar -Dspring.profiles.active=prod /opt/app/bill-payment.jar"
    ports:
      - "8080"
    networks:
      - wallet-db
      - wallet-rabbit
      - wallet
